wandb_version: 1

K:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
activation_function:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: naive
device:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 0.1
embed_dim:
  desc: null
  value: 128
env:
  desc: null
  value: mlens
learning_rate:
  desc: null
  value: 0.001
log_to_wandb:
  desc: null
  value: true
max_ep_len:
  desc: null
  value: 100
max_iters:
  desc: null
  value: 10
mode:
  desc: null
  value: normal
model_type:
  desc: null
  value: dt
n_head:
  desc: null
  value: 1
n_layer:
  desc: null
  value: 3
num_eval_episodes:
  desc: null
  value: 20
num_steps_per_iter:
  desc: null
  value: 10
pct_traj:
  desc: null
  value: 1.0
use_personalized_embeddings:
  desc: null
  value: 'no'
use_prev_temp_as_feature:
  desc: null
  value: 'no'
warmup_steps:
  desc: null
  value: 10000
weight_decay:
  desc: null
  value: 0.0001
